feat: ES Modules
semantic-release/git pull request #526
Opened 2024-10-11 17:59 UTC by babblebey

This PR converts the plugin to ESM only.

Related to https://github.com/semantic-release/semantic-release/issues/2133

BREAKING CHANGE: `@semantic-release/git` is now a native ES Module. It has named exports for each plugin hook (verifyConditions, prepare)

2026-03-13 21:03 UTC, travi commented on .github/workflows/test.yml
> +        run: exit 1
this is a good example to follow for the changelog update

2026-03-13 21:06 UTC, babblebey commented on .github/workflows/test.yml
> +        run: exit 1
Very well,

Attn to the failing workflows, I don't seem to understand them... A little light there please 🤔

2026-03-13 21:09 UTC, travi requested changes
i just spot the one adjustment. then i think this is good to go. thanks a ton for the investment into getting these updated!

2026-03-13 21:09 UTC, travi commented on lib/definitions/errors.js
> +const { homepage } = require("../../package.json");
lets avoid `createRequire` here like the changelog change

2026-03-13 22:38 UTC, travi commented
> Attn to the failing workflows, I don't seem to understand them... A little light there please 🤔

it looks like execa is making a true git call, which i would be surprised if it was doing that before. i havent looked deep enough to confirm that or what might need to change. my first thought was to check if there is an execa update available that was unblocked by the esm change, but it looks like youve already updated to the latest major. maybe there was a breaking change, or even just the nature or the esm change, that changed the way that was previously stubbed to allow the call through when it wasnt doing that before

2026-03-15 01:13 UTC, babblebey commented
> it looks like execa is making a true git call, which i would be surprised if it was doing that before.

I don't know how the tests have been passing originally.... but I just found some error relating to the CI runner not having a global git `user.name`/`user.email` configured, and the test helpers don't mock them before repo operations.

2026-03-27 18:29 UTC, travi commented on test/helpers/git-utils.js
> +  await execa("git", ["config", "user.name", "Test"], { cwd });
while i understand that this gets the tests working, are we certain this doesnt impact your personal config when running locally? if it is isolated from impacting that, can you help me understand how?

2026-06-26 21:01 UTC, babblebey commented on test/helpers/git-utils.js
> +  await execa("git", ["config", "user.name", "Test"], { cwd });
Yup this doesn't mess with personal git config!

These commands only set repository-local git config in the temporary test repo (via cwd),  they do not touch the global config. Since we do not pass `--global` flag to the execa commant, personal git configs are not modified.

2026-07-17 19:47 UTC, travi approved these changes

2026-07-17 19:49 UTC, travi commented on package.json
> +    "node": "^22.14.0 || >= 24.10.0"
maybe one last change for this, but this could be after merging to beta. i've been finding some packages needing even higher node version minimums, so i've been using `^22.22.2 || >=24.15` lately

2026-07-17 20:01 UTC, babblebey commented on package.json
> +    "node": "^22.14.0 || >= 24.10.0"
> so i've been using `^22.22.2 || >=24.15` lately

Very well, Kindly list'em up in an issue or discuss, so we can appropriate

2026-07-17 21:16 UTC, merged